name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        source-url: https://nuget.pkg.github.com/michealw/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: | 
        dotnet build --no-restore
        dotnet pack -c Release -o out
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish to GH Packages
      run: dotnet nuget push ./out/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }}
